import type { Show } from "./types";

/**
 * Curated shows powering the public read-only demo (`/demo`). Framed as a shared
 * map for three people: "You" is a real concert history (imported), plus two
 * sample friends (Maya, Leo) so the per-attendee colors and Friends toggle demo
 * well. Rendered directly, never touching Supabase.
 */

export interface Attendee {
  id: string;
  label: string;
  color: string;
}

export const DEMO_PEOPLE: Attendee[] = [
  { id: "you", label: "You", color: "#4f46e5" },
  { id: "maya", label: "Maya", color: "#ec4899" },
  { id: "leo", label: "Leo", color: "#f59e0b" },
];

interface DemoSeed {
  attendee: string;
  artist: string;
  venue: string;
  city: string;
  country: string;
  show_date: string;
  latitude: number;
  longitude: number;
  notes?: string;
  setlist: string[];
  photos?: string[];
  videos?: string[];
}

const SEED: DemoSeed[] = [
  {
    "attendee": "you",
    "artist": "Sonic Youth",
    "venue": "Central Park SummerStage",
    "city": "New York",
    "country": "United States",
    "show_date": "2003-06-27",
    "latitude": 40.7142691,
    "longitude": -74.0059729,
    "setlist": [
      "She Is Not Alone",
      "Rain on Tin",
      "Drunken Butterfly",
      "Radical Adults Lick Godhead Style",
      "Kim Gordon and the Arthur Doyle Hand Cream",
      "Skip Tracer",
      "Disconnection Notice",
      "Plastic Sun",
      "Karen Revisited",
      "Peace Attack",
      "The Empty Page",
      "Sympathy for the Strawberry",
      "Expressway to Yr Skull"
    ]
  },
  {
    "attendee": "you",
    "artist": "Sigur Rós",
    "venue": "The Music Center at Strathmore",
    "city": "North Bethesda",
    "country": "United States",
    "show_date": "2005-09-11",
    "latitude": 39.0445535,
    "longitude": -77.1188678,
    "setlist": [
      "Takk...",
      "Glósóli",
      "Ný batterí",
      "Svefn-g-englar",
      "Sæglópur",
      "Hoppípolla",
      "Með blóðnasir",
      "Untitled #1 – Vaka",
      "Untitled #4 – Njósnavélin",
      "Viðrar vel til loftárása",
      "Smáskifa",
      "Untitled #8 – Popplagið"
    ]
  },
  {
    "attendee": "you",
    "artist": "Echo & the Bunnymen",
    "venue": "Zappa Club",
    "city": "Tel Aviv",
    "country": "Israel",
    "show_date": "2006-03-08",
    "latitude": 32.0666667,
    "longitude": 34.7666667,
    "setlist": [
      "Over the Wall",
      "Show of Strength",
      "Stormy Weather",
      "Bring On the Dancing Horses",
      "Seven Seas",
      "The Disease",
      "Scissors in the Sand",
      "Crocodiles",
      "The Back of Love",
      "The Killing Moon",
      "In the Margins",
      "Crocodiles",
      "Villiers Terrace",
      "Never Stop",
      "Rescue",
      "The Cutter",
      "Nothing Lasts Forever",
      "Lips Like Sugar",
      "Ocean Rain"
    ]
  },
  {
    "attendee": "you",
    "artist": "Echo & the Bunnymen",
    "venue": "Reading 3",
    "city": "Tel Aviv",
    "country": "Israel",
    "show_date": "2011-04-29",
    "latitude": 32.0666667,
    "longitude": 34.7666667,
    "setlist": [
      "Going Up",
      "Show of Strength",
      "Rescue",
      "Villiers Terrace",
      "Bedbugs and Ballyhoo",
      "Seven Seas",
      "Bring On the Dancing Horses",
      "Silver",
      "The Disease",
      "All That Jazz",
      "Think I Need It Too",
      "Never Stop",
      "All My Colours (Zimbo)",
      "The Back of Love",
      "The Killing Moon",
      "The Cutter",
      "Nothing Lasts Forever",
      "The Fountain",
      "Lips Like Sugar",
      "In the Margins",
      "Over the Wall",
      "Do It Clean"
    ]
  },
  {
    "attendee": "you",
    "artist": "Bob Dylan",
    "venue": "Ramat Gan Stadium",
    "city": "Ramat Gan",
    "country": "Israel",
    "show_date": "2011-06-20",
    "latitude": 32.0805556,
    "longitude": 34.8141667,
    "setlist": [
      "Gonna Change My Way of Thinking",
      "It's All Over Now, Baby Blue",
      "Things Have Changed",
      "Tangled Up in Blue",
      "Summer Days",
      "Simple Twist of Fate",
      "Cold Irons Bound",
      "A Hard Rain's A-Gonna Fall",
      "Highway 61 Revisited",
      "Forgetful Heart",
      "Thunder on the Mountain",
      "Ballad of a Thin Man",
      "Like a Rolling Stone",
      "All Along the Watchtower",
      "Blowin' in the Wind"
    ]
  },
  {
    "attendee": "you",
    "artist": "Morrissey",
    "venue": "Bitan 1",
    "city": "Tel Aviv",
    "country": "Israel",
    "show_date": "2012-07-21",
    "latitude": 32.0666667,
    "longitude": 34.7666667,
    "setlist": [
      "How Soon Is Now?",
      "Everyday Is Like Sunday",
      "You're the One for Me, Fatty",
      "You Have Killed Me",
      "Shoplifters of the World Unite",
      "Ouija Board, Ouija Board",
      "People Have the Power",
      "Maladjusted",
      "I'm Throwing My Arms Around Paris",
      "I Know It's Over",
      "Black Cloud",
      "Alma Matters",
      "When Last I Spoke to Carol",
      "Last Night I Dreamt That Somebody Loved Me",
      "One Day Goodbye Will Be Farewell",
      "To Give (The Reason I Live)",
      "Speedway",
      "Still Ill",
      "Meat Is Murder",
      "Let Me Kiss You",
      "I Will See You in Far-Off Places"
    ]
  },
  {
    "attendee": "you",
    "artist": "My Bloody Valentine",
    "venue": "Parc del Fòrum",
    "city": "Barcelona",
    "country": "Spain",
    "show_date": "2013-05-25",
    "latitude": 41.3887868890716,
    "longitude": 2.15898513793945,
    "setlist": [
      "I Only Said",
      "When You Sleep",
      "New You",
      "You Never Should",
      "Honey Power",
      "Only Tomorrow",
      "Come In Alone",
      "Only Shallow",
      "Thorn",
      "To Here Knows When",
      "Soon",
      "Feed Me With Your Kiss",
      "You Made Me Realise"
    ]
  },
  {
    "attendee": "you",
    "artist": "The Rolling Stones",
    "venue": "Park HaYarkon",
    "city": "Tel Aviv",
    "country": "Israel",
    "show_date": "2014-06-04",
    "latitude": 32.0666667,
    "longitude": 34.7666667,
    "setlist": [
      "Start Me Up",
      "You Got Me Rocking",
      "It's Only Rock 'n' Roll (but I Like It)",
      "Tumbling Dice",
      "Angie",
      "Doom and Gloom",
      "Get Off of My Cloud",
      "Paint It Black",
      "Honky Tonk Women",
      "You Got the Silver",
      "Can't Be Seen",
      "Midnight Rambler",
      "Miss You",
      "Gimme Shelter",
      "Jumpin' Jack Flash",
      "Sympathy for the Devil",
      "Brown Sugar",
      "You Can't Always Get What You Want",
      "(I Can't Get No) Satisfaction"
    ]
  },
  {
    "attendee": "you",
    "artist": "Massive Attack",
    "venue": "Parc Georges-Valbon",
    "city": "La Courneuve",
    "country": "France",
    "show_date": "2014-09-12",
    "latitude": 48.917,
    "longitude": 2.383,
    "setlist": [
      "Battle Box",
      "United Snakes",
      "Risingson",
      "Paradise Circus",
      "Girl I Love You",
      "Psyche",
      "Future Proof",
      "Teardrop",
      "Angel",
      "Jupiter",
      "Inertia Creeps",
      "Safe From Harm",
      "Incantations",
      "Splitting the Atom",
      "Unfinished Sympathy"
    ]
  },
  {
    "attendee": "you",
    "artist": "Sebadoh",
    "venue": "Circolo degli Artisti",
    "city": "Rome",
    "country": "Italy",
    "show_date": "2014-10-24",
    "latitude": 41.9,
    "longitude": 12.483,
    "setlist": [
      "Magnet's Coil",
      "Rebound",
      "Skull",
      "The Freed Pig",
      "Arbitrary High",
      "Love You Here",
      "I Will",
      "Drag Down",
      "Careful",
      "Not Too Amused",
      "Defend Yr Self",
      "Got It",
      "My Drugs",
      "Inquiries",
      "Vampire",
      "Beauty of the Ride",
      "Soul and Fire",
      "State of Mine",
      "Keep the Boy Alive",
      "License to Confuse",
      "On Fire",
      "Brand New Love"
    ]
  },
  {
    "attendee": "you",
    "artist": "Luna",
    "venue": "Barby Club",
    "city": "Tel Aviv",
    "country": "Israel",
    "show_date": "2015-08-05",
    "latitude": 32.0666667,
    "longitude": 34.7666667,
    "setlist": [
      "Slide",
      "Chinatown",
      "Sideshow by the Seashore",
      "Malibu Love Nest",
      "Tiger Lily",
      "Tracy I Love You",
      "Pup Tent",
      "Bewitched",
      "Friendly Advice",
      "Blue Thunder",
      "Tugboat",
      "Strange",
      "Moon Palace",
      "23 Minutes in Brussels",
      "Indian Summer",
      "Ceremony",
      "Sweet Child o' Mine",
      "Anesthesia"
    ]
  },
  {
    "attendee": "you",
    "artist": "Radiohead",
    "venue": "Park HaYarkon",
    "city": "Tel Aviv",
    "country": "Israel",
    "show_date": "2017-07-19",
    "latitude": 32.0666667,
    "longitude": 34.7666667,
    "setlist": [
      "Daydreaming",
      "Lucky",
      "Ful Stop",
      "Airbag",
      "15 Step",
      "Myxomatosis",
      "All I Need",
      "Pyramid Song",
      "Everything in Its Right Place",
      "Let Down",
      "Bloom",
      "Identikit",
      "Weird Fishes/Arpeggi",
      "The Numbers",
      "2 + 2 = 5",
      "Bodysnatchers",
      "Idioteque",
      "No Surprises",
      "Nude",
      "Like Spinning Plates",
      "Lotus Flower",
      "Paranoid Android",
      "Reckoner",
      "Creep",
      "The Bends",
      "There There",
      "Karma Police"
    ]
  },
  {
    "attendee": "you",
    "artist": "Slowdive",
    "venue": "Barby Club",
    "city": "Tel Aviv",
    "country": "Israel",
    "show_date": "2017-09-07",
    "latitude": 32.0666667,
    "longitude": 34.7666667,
    "setlist": [
      "Slomo",
      "Slowdive",
      "Catch the Breeze",
      "Crazy for You",
      "Star Roving",
      "Avalyn",
      "Machine Gun",
      "Souvlaki Space Station",
      "When the Sun Hits",
      "Alison",
      "Sugar for the Pill",
      "No Longer Making Time",
      "Golden Hair",
      "Blue Skied an' Clear",
      "Dagger",
      "40 Days"
    ]
  },
  {
    "attendee": "you",
    "artist": "Deerhunter",
    "venue": "Kesselhaus",
    "city": "Berlin",
    "country": "Germany",
    "show_date": "2019-11-17",
    "latitude": 52.5166667,
    "longitude": 13.4,
    "setlist": [
      "Death in Midsummer",
      "No One's Sleeping",
      "Revival",
      "Desire Lines",
      "Sailing",
      "Take Care",
      "Futurism",
      "Plains",
      "Coronado",
      "Nocturne",
      "Agoraphobia",
      "Cover Me (Slowly)",
      "He Would Have Laughed"
    ]
  },
  {
    "attendee": "you",
    "artist": "Big Thief",
    "venue": "Wiltern Theatre",
    "city": "Los Angeles",
    "country": "United States",
    "show_date": "2022-05-10",
    "latitude": 34.052,
    "longitude": -118.244,
    "setlist": [
      "Forgotten Eyes",
      "Black Diamonds",
      "Masterpiece",
      "Shoulders",
      "Real Love",
      "Bruiser",
      "Flower of Blood",
      "Dragon New Warm Mountain I Believe in You",
      "Not",
      "happiness",
      "Wanted You to Stay",
      "Sadness as a Gift",
      "Certainty",
      "Spud Infinity",
      "Cactus Practice",
      "Cattails"
    ]
  },
  {
    "attendee": "you",
    "artist": "The Murder Capital",
    "venue": "Lost Lake Lounge",
    "city": "Denver",
    "country": "United States",
    "show_date": "2023-04-07",
    "latitude": 39.7391536,
    "longitude": -104.9847034,
    "setlist": [
      "For Everything",
      "More Is Less",
      "Return My Head",
      "Green & Blue",
      "A Thousand Lives",
      "The Stars Will Leave Their Stage",
      "Crying",
      "Slowdance I",
      "Slowdance II",
      "The Lie Becomes the Self",
      "Love, Love, Love",
      "Gigi's Recovery",
      "Feeling Fades",
      "Only Good Things",
      "Don't Cling to Life",
      "Ethel"
    ]
  },
  {
    "attendee": "you",
    "artist": "Morrissey",
    "venue": "Expo Tel Aviv",
    "city": "Tel Aviv",
    "country": "Israel",
    "show_date": "2023-07-04",
    "latitude": 32.0666667,
    "longitude": 34.7666667,
    "setlist": [
      "How Soon Is Now?",
      "Suedehead",
      "Alma Matters",
      "Our Frank",
      "Girlfriend in a Coma",
      "I'm Throwing My Arms Around Paris",
      "Notre-Dame",
      "Sure Enough, the Telephone Rings",
      "Knockabout World",
      "I Wish You Lonely",
      "Half a Person",
      "My Hurling Days Are Done",
      "The Night Pop Dropped",
      "Stop Me If You Think You've Heard This One Before",
      "Everyday Is Like Sunday",
      "Please, Please, Please Let Me Get What I Want",
      "The Loop",
      "Jack the Ripper",
      "Irish Blood, English Heart"
    ]
  },
  {
    "attendee": "you",
    "artist": "Blur",
    "venue": "Ex Campo Balilla, Mura di Lucca",
    "city": "Lucca",
    "country": "Italy",
    "show_date": "2023-07-22",
    "latitude": 43.8435654491906,
    "longitude": 10.5058479309082,
    "setlist": [
      "The Debt Collector",
      "St. Charles Square",
      "There's No Other Way",
      "Popscene",
      "Tracy Jacks",
      "Beetlebum",
      "Trimm Trabb",
      "Villa Rosie",
      "Intermission",
      "Coffee & TV",
      "End of a Century",
      "Country House",
      "Parklife",
      "To the End",
      "Oily Water",
      "Advert",
      "Song 2",
      "The Narcissist",
      "This Is a Low",
      "Barbaric",
      "Girls & Boys",
      "For Tomorrow",
      "Tender",
      "The Universal"
    ]
  },
  {
    "attendee": "you",
    "artist": "Public Image Ltd",
    "venue": "Chalk",
    "city": "Brighton",
    "country": "United Kingdom",
    "show_date": "2023-09-26",
    "latitude": 50.8283849472495,
    "longitude": -0.139474868774414,
    "setlist": [
      "Penge",
      "Albatross",
      "Being Stupid Again",
      "This Is Not a Love Song",
      "Poptones",
      "Death Disco",
      "The Room I Am In",
      "Flowers of Romance",
      "Memories",
      "Car Chase",
      "The Body",
      "Warrior",
      "Shoom",
      "Public Image",
      "Open Up",
      "Rise"
    ],
    "notes": "Gili's Bat Mtzva Trip!"
  },
  {
    "attendee": "you",
    "artist": "PJ Harvey",
    "venue": "Roundhouse",
    "city": "London",
    "country": "United Kingdom",
    "show_date": "2023-09-28",
    "latitude": 51.5084152563931,
    "longitude": -0.125532746315002,
    "setlist": [
      "Prayer at the Gate",
      "Autumn Term",
      "Lwonesome Tonight",
      "Seem an I",
      "The Nether-Edge",
      "I Inside the Old Year Dying",
      "All Souls",
      "A Child's Question, August",
      "I Inside the Old I Dying",
      "August",
      "A Child's Question, July",
      "A Noiseless Noise",
      "The Colour of the Earth",
      "The Glorious Land",
      "The Words That Maketh Murder",
      "Angelene",
      "Send His Love to Me",
      "The Garden",
      "The Desperate Kingdom of Love",
      "Man-Size",
      "Dress",
      "Down by the Water",
      "To Bring You My Love",
      "C'mon Billy",
      "White Chalk"
    ]
  },
  {
    "attendee": "you",
    "artist": "Dinosaur Jr.",
    "venue": "The Garage",
    "city": "London",
    "country": "United Kingdom",
    "show_date": "2023-11-12",
    "latitude": 51.5084152563931,
    "longitude": -0.125532746315002,
    "setlist": [
      "Out There",
      "Start Choppin",
      "What Else Is New",
      "On the Way",
      "Not the Same",
      "Get Me",
      "Drawerings",
      "Hide",
      "Goin' Home",
      "I Ain't Sayin'",
      "Garden",
      "The Lung",
      "Freak Scene",
      "Feel the Pain",
      "Gargoyle",
      "T.V. Eye",
      "No Fun"
    ]
  },
  {
    "attendee": "you",
    "artist": "The Jesus and Mary Chain",
    "venue": "Chalk",
    "city": "Brighton",
    "country": "United Kingdom",
    "show_date": "2023-11-16",
    "latitude": 50.8283849472495,
    "longitude": -0.139474868774414,
    "setlist": [
      "Blues From a Gun",
      "Head On",
      "April Skies",
      "Between Planets",
      "Amputation",
      "Cracking Up",
      "Snakedriver",
      "Taste of Cindy",
      "Happy When It Rains",
      "Halfway to Crazy",
      "Some Candy Talking",
      "All Things Must Pass",
      "Nine Million Rainy Days",
      "Darklands",
      "Sometimes Always",
      "Just Like Honey",
      "I Hate Rock 'n' Roll",
      "Reverence"
    ]
  },
  {
    "attendee": "you",
    "artist": "The Beta Band",
    "venue": "Brooklyn Steel",
    "city": "Brooklyn",
    "country": "United States",
    "show_date": "2025-11-01",
    "latitude": 40.65,
    "longitude": -73.95,
    "setlist": [
      "Memory of a Free Festival",
      "Inner Meet Me",
      "She's the One",
      "It's Not Too Beautiful",
      "Assessment",
      "Alleged",
      "Push It Out",
      "Needles in My Eyes",
      "Dog's Got a Bone",
      "Dr. Baker",
      "B + A",
      "Dry the Rain",
      "Broke",
      "I Know",
      "Squares",
      "The House Song"
    ]
  },
  {
    "attendee": "you",
    "artist": "Panda Bear",
    "venue": "Auditori Rockdelux",
    "city": "Barcelona",
    "country": "Spain",
    "show_date": "2026-06-04",
    "latitude": 41.3887868890716,
    "longitude": 2.15898513793945,
    "setlist": [
      "Shepard Tone",
      "Song for Ariel",
      "Sequential Circuits",
      "Ferry Lady",
      "Anywhere but Here",
      "Boneless",
      "Tomboy",
      "Inner Monologue",
      "Ends Meet",
      "Virginia Tech",
      "Just as Well",
      "Slow Motion"
    ],
    "notes": "With Amit , Nani, Neta and Lior"
  },
  {
    "attendee": "you",
    "artist": "Slowdive",
    "venue": "Revolut",
    "city": "Barcelona",
    "country": "Spain",
    "show_date": "2026-06-05",
    "latitude": 41.3887868890716,
    "longitude": 2.15898513793945,
    "setlist": [
      "shanty",
      "Star Roving",
      "Catch the Breeze",
      "Crazy for You",
      "Souvlaki Space Station",
      "Slomo",
      "kisses",
      "Sugar for the Pill",
      "Alison",
      "When the Sun Hits"
    ]
  },
  {
    "attendee": "you",
    "artist": "My Bloody Valentine",
    "venue": "Estrella Damm",
    "city": "Barcelona",
    "country": "Spain",
    "show_date": "2026-06-06",
    "latitude": 41.3887868890716,
    "longitude": 2.15898513793945,
    "setlist": [
      "I Only Said",
      "When You Sleep",
      "New You",
      "You Never Should",
      "Thorn",
      "Cigarette in Your Bed",
      "Only Tomorrow",
      "Only Shallow",
      "To Here Knows When",
      "Slow",
      "Soon",
      "Wonder 2",
      "Feed Me With Your Kiss",
      "You Made Me Realise"
    ]
  },
  {
    "attendee": "you",
    "artist": "Big Thief",
    "venue": "Estrella Damm",
    "city": "Barcelona",
    "country": "Spain",
    "show_date": "2026-06-06",
    "latitude": 41.3887868890716,
    "longitude": 2.15898513793945,
    "setlist": [
      "Forgive the Dream",
      "Double Infinity",
      "Shark Smile",
      "Mr. Man",
      "Words",
      "Simulation Swarm",
      "Not",
      "Christmas Day",
      "Vampire Empire",
      "Change",
      "Beautiful World",
      "Incomprehensible",
      "Spud Infinity"
    ]
  },
  {
    "attendee": "you",
    "artist": "Nick Cave & the Bad Seeds",
    "venue": "Plateia Nerou",
    "city": "Piraeus",
    "country": "Greece",
    "show_date": "2026-06-24",
    "latitude": 37.9474464019929,
    "longitude": 23.6370849609375,
    "setlist": [
      "Get Ready for Love",
      "From Her to Eternity",
      "Train Long-Suffering",
      "Wild God",
      "O Children",
      "Tupelo",
      "Carnage",
      "Joy",
      "Rings of Saturn",
      "Bright Horses",
      "Henry Lee",
      "The Mercy Seat",
      "Papa Won't Leave You, Henry",
      "Red Right Hand",
      "Jubilee Street",
      "Hiding All Away / White Elephant",
      "Hollywood",
      "City of Refuge",
      "The Weeping Song",
      "Wide Lovely Eyes",
      "Nobody's Baby Now",
      "Into My Arms"
    ],
    "videos": [
      "myXV3FGzMvE"
    ]
  },
  {
    "attendee": "maya",
    "artist": "Beyoncé",
    "venue": "Wembley Stadium",
    "city": "London",
    "country": "United Kingdom",
    "show_date": "2016-07-02",
    "latitude": 51.556,
    "longitude": -0.2796,
    "setlist": [
      "Formation",
      "Sorry",
      "Hold Up",
      "Crazy in Love",
      "Halo"
    ],
    "photos": [
      "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&q=80"
    ],
    "videos": [
      "bnVUHWCynig"
    ]
  },
  {
    "attendee": "maya",
    "artist": "Rosalía",
    "venue": "Razzmatazz",
    "city": "Barcelona",
    "country": "Spain",
    "show_date": "2019-07-12",
    "latitude": 41.3979,
    "longitude": 2.1929,
    "setlist": [
      "Malamente",
      "Pienso en tu mirá",
      "Di Mi Nombre",
      "A Palé",
      "Con Altura"
    ]
  },
  {
    "attendee": "maya",
    "artist": "Kaytranada",
    "venue": "Palacio de Deportes",
    "city": "Mexico City",
    "country": "Mexico",
    "show_date": "2022-11-19",
    "latitude": 19.4053,
    "longitude": -99.0993,
    "setlist": [
      "10%",
      "Freefall",
      "Glowed Up",
      "Lite Spots"
    ]
  },
  {
    "attendee": "maya",
    "artist": "Florence + the Machine",
    "venue": "Ziggo Dome",
    "city": "Amsterdam",
    "country": "Netherlands",
    "show_date": "2022-11-12",
    "latitude": 52.3139,
    "longitude": 4.9375,
    "setlist": [
      "King",
      "Ship to Wreck",
      "Dog Days Are Over",
      "Shake It Out",
      "Rabbit Heart"
    ]
  },
  {
    "attendee": "maya",
    "artist": "Bad Bunny",
    "venue": "Estadio Monumental",
    "city": "Santiago",
    "country": "Chile",
    "show_date": "2025-02-11",
    "latitude": -33.5089,
    "longitude": -70.6053,
    "setlist": [
      "Tití Me Preguntó",
      "Me Porto Bonito",
      "Yonaguni",
      "Dákiti",
      "Callaíta"
    ]
  },
  {
    "attendee": "leo",
    "artist": "Kendrick Lamar",
    "venue": "Accor Arena",
    "city": "Paris",
    "country": "France",
    "show_date": "2017-02-27",
    "latitude": 48.8386,
    "longitude": 2.3785,
    "setlist": [
      "DNA.",
      "ELEMENT.",
      "King Kunta",
      "HUMBLE.",
      "Alright"
    ]
  },
  {
    "attendee": "leo",
    "artist": "The Strokes",
    "venue": "Barclays Center",
    "city": "Brooklyn",
    "country": "United States",
    "show_date": "2020-01-01",
    "latitude": 40.6826,
    "longitude": -73.9754,
    "setlist": [
      "Bad Decisions",
      "The Adults Are Talking",
      "Reptilia",
      "Last Nite",
      "Hard to Explain"
    ]
  },
  {
    "attendee": "leo",
    "artist": "The Weeknd",
    "venue": "MetLife Stadium",
    "city": "East Rutherford",
    "country": "United States",
    "show_date": "2023-08-27",
    "latitude": 40.8135,
    "longitude": -74.0745,
    "setlist": [
      "Take My Breath",
      "Blinding Lights",
      "Save Your Tears",
      "Starboy",
      "The Hills"
    ],
    "videos": [
      "4NRXx6U8ABQ"
    ]
  },
  {
    "attendee": "leo",
    "artist": "Fred again..",
    "venue": "Sydney Opera House Forecourt",
    "city": "Sydney",
    "country": "Australia",
    "show_date": "2024-02-24",
    "latitude": -33.8568,
    "longitude": 151.2153,
    "setlist": [
      "Delilah (pull me out of this)",
      "Rumble",
      "Turn On the Lights again..",
      "Marea (we've lost dancing)"
    ]
  }
];

export const DEMO_SHOWS: Show[] = SEED.map((s, i) => {
  const id = `demo-${i + 1}`;
  const media = [
    ...(s.photos ?? []).map((url, j) => ({
      id: `${id}-photo-${j + 1}`,
      show_id: id,
      kind: "photo" as const,
      storage_path: null,
      youtube_id: null,
      caption: null,
      position: j,
      url,
    })),
    ...(s.videos ?? []).map((vid, j) => ({
      id: `${id}-video-${j + 1}`,
      show_id: id,
      kind: "video" as const,
      storage_path: null,
      youtube_id: vid,
      caption: null,
      position: (s.photos?.length ?? 0) + j,
    })),
  ];
  return {
    id,
    user_id: s.attendee,
    artist: s.artist,
    venue: s.venue,
    city: s.city,
    country: s.country,
    latitude: s.latitude,
    longitude: s.longitude,
    show_date: s.show_date,
    notes: s.notes ?? null,
    created_at: `${s.show_date}T00:00:00.000Z`,
    setlist_songs: s.setlist.map((title, j) => ({
      id: `${id}-song-${j + 1}`,
      show_id: id,
      position: j + 1,
      title,
    })),
    show_media: media,
  };
});

/** Handle shown in the demo chrome. */
export const DEMO_HANDLE = "demo";
